# Generated by Django 5.1.4 on 2024-12-20 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_shoppingcartitem_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='shopping_cart',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='shopping_card_items',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.shoppingcartitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppingcartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.product'),
        ),
    ]
