# Generated by Django 5.1.4 on 2024-12-20 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_shoppingcartitem_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='shopping_card_items',
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='shopping_cart',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='store.shoppingcart'),
            preserve_default=False,
        ),
    ]
