# Generated by Django 5.1.4 on 2024-12-20 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_shoppingcart_shopping_card_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcartitem',
            old_name='shopping_cart',
            new_name='cart',
        ),
    ]
